### ISSUE TITLE
Install instructions stack

### ISSUE THREAD

**Issue by turion** [mheinzel/clash-yosys-icestick-examples#1]
Your install instructions fail on nixos-unstable:

```
$ stack install --resolver lts-12.12 clash-ghc
Downloaded lts-12.12 build plan.    
error: attribute 'ghc843' missing, at (string):1:43
(use '--show-trace' to show detailed location information)
```

**Comment by turion** [comment]
Resolution seems to be to update the makefile to `lts-12.26`.

**Comment by turion** [comment]
(And the Readme, of course)

**Comment by mheinzel** [comment]
Is this due to the Nix integration of Stack? Does Stack on NixOs try to install GHC through Nix by default?

I bumped the LTS as suggested.

**Comment by turion** [comment]
Yes, NixOS requires `system-ghc: true` and therefore allows only those versions available through nix.

**Comment by mheinzel** [comment]
Seems like this is solved. Thanks for opening the issue!
